/***********************************************************************************
* Disassembles machine code for the target platform of the Intel 8080 microprocessor
* @Author: Andrew Gunter
***********************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Global variable definitions and function prototypes
char instructions[256][20];
char instructionSizes[256];
char instructionFlags[256][20];
char instructionFunctions[256][100];
void initializeGlobals();

/**
* Main function
*/
int main(int argc, char **argv)
{
    int pc = 0;  // Program Counter
    unsigned char *romBuffer;  // Buffer for storing bytes read from Space Invaders ROM
    int romSizeInBytes = 0;
    initializeGlobals();

    // Open Space Invaders ROM file
    FILE *invadersFile = fopen("invaders.h", "rb");  // binary file read-only

    if(invadersFile == NULL){
        printf("Failed to open Space Invaders ROM.");
        return -1;
    }

    // Get ROM size
    fseek(invadersFile, 0, SEEK_END);
    romSizeInBytes = ftell(invadersFile);
    fseek(invadersFile, 0, SEEK_SET);

    // Allocate memory for ROM
    romBuffer = malloc(romSizeInBytes);

    // Read ROM into buffer
    fread(romBuffer, 1, romSizeInBytes, invadersFile);
    
    // Disassemble machine code into Intel 8080 assembly language instructions
    unsigned char operation;
    char instruction[20];
    int instructionSize;
    char instructionFlag[20];
    char instructionFunction[100];
    int instructionCounter = 0;
    while(pc < romSizeInBytes){
        // Get next operation
        operation = romBuffer[pc];

        // Disassemble operation based on Lookup Tables (arrays indexed by opcode)
        instructionSize = instructionSizes[operation];
        memcpy(instruction, instructions[operation], 20);
        memcpy(instructionFlag, instructionFlags[operation], 20);
        memcpy(instructionFunction, instructionFunctions[operation], 100);

        // Print disassembled assembly instruction
        printf("Instruction Number %d\n", instructionCounter);
        printf("%s\n", instruction);
        printf("%s\n", instructionFunction);
        printf("%s\n\n", instructionFlag);

        pc += instructionSize;
        instructionCounter++;
	}

    free(romBuffer);
    return 0;
}

/**
* Initialize global variables.
* 
* I do this here because the initializations are about 1000 lines.
* I could do this elsewhere, but it would clutter the top of the file.
* Relegate initialization to a function so it can happily remain at the bottom of the file.
* 
* @return void
*/
void initializeGlobals()
{
    char instructionsLocal[256][20] = {
        "NOP",
        "LXI B;D16",
        "STAX B",
        "INX B",
        "INR B",
        "DCR B",
        "MVI B; D8",
        "RLC",
        "-",
        "DAD B",
        "LDAX B",
        "DCX B",
        "INR C",
        "DCR C",
        "MVI C;D8",
        "RRC",
        "-",
        "LXI D;D16",
        "STAX D",
        "INX D",
        "INR D",
        "DCR D",
        "MVI D; D8",
        "RAL",
        "-",
        "DAD D",
        "LDAX D",
        "DCX D",
        "INR E",
        "DCR E",
        "MVI E;D8",
        "RAR",
        "RIM",
        "LXI H;D16",
        "SHLD adr",
        "INX H",
        "INR H",
        "DCR H",
        "MVI H;D8",
        "DAA",
        "-",
        "DAD H",
        "LHLD adr",
        "DCX H",
        "INR L",
        "DCR L",
        "MVI L; D8",
        "CMA",
        "SIM",
        "LXI SP; D16",
        "STA adr",
        "INX SP",
        "INR M",
        "DCR M",
        "MVI M;D8",
        "STC",
        "-",
        "DAD SP",
        "LDA adr",
        "DCX SP",
        "INR A",
        "DCR A",
        "MVI A;D8",
        "CMC",
        "MOV B;B",
        "MOV B;C",
        "MOV B;D",
        "MOV B;E",
        "MOV B;H",
        "MOV B;L",
        "MOV B;M",
        "MOV B;A",
        "MOV C;B",
        "MOV C;C",
        "MOV C;D",
        "MOV C;E",
        "MOV C;H",
        "MOV C;L",
        "MOV C;M",
        "MOV C;A",
        "MOV D;B",
        "MOV D;C",
        "MOV D;D",
        "MOV D;E",
        "MOV D;H",
        "MOV D;L",
        "MOV D;M",
        "MOV D;A",
        "MOV E;B",
        "MOV E;C",
        "MOV E;D",
        "MOV E;E",
        "MOV E;H",
        "MOV E;L",
        "MOV E;M",
        "MOV E;A",
        "MOV H;B",
        "MOV H;C",
        "MOV H;D",
        "MOV H;E",
        "MOV H;H",
        "MOV H;L",
        "MOV H;M",
        "MOV H;A",
        "MOV L;B",
        "MOV L;C",
        "MOV L;D",
        "MOV L;E",
        "MOV L;H",
        "MOV L;L",
        "MOV L;M",
        "MOV L;A",
        "MOV M;B",
        "MOV M;C",
        "MOV M;D",
        "MOV M;E",
        "MOV M;H",
        "MOV M;L",
        "HLT",
        "MOV M;A",
        "MOV A;B",
        "MOV A;C",
        "MOV A;D",
        "MOV A;E",
        "MOV A;H",
        "MOV A;L",
        "MOV A;M",
        "MOV A;A",
        "ADD B",
        "ADD C",
        "ADD D",
        "ADD E",
        "ADD H",
        "ADD L",
        "ADD M",
        "ADD A",
        "ADC B",
        "ADC C",
        "ADC D",
        "ADC E",
        "ADC H",
        "ADC L",
        "ADC M",
        "ADC A",
        "SUB B",
        "SUB C",
        "SUB D",
        "SUB E",
        "SUB H",
        "SUB L",
        "SUB M",
        "SUB A",
        "SBB B",
        "SBB C",
        "SBB D",
        "SBB E",
        "SBB H",
        "SBB L",
        "SBB M",
        "SBB A",
        "ANA B",
        "ANA C",
        "ANA D",
        "ANA E",
        "ANA H",
        "ANA L",
        "ANA M",
        "ANA A",
        "XRA B",
        "XRA C",
        "XRA D",
        "XRA E",
        "XRA H",
        "XRA L",
        "XRA M",
        "XRA A",
        "ORA B",
        "ORA C",
        "ORA D",
        "ORA E",
        "ORA H",
        "ORA L",
        "ORA M",
        "ORA A",
        "CMP B",
        "CMP C",
        "CMP D",
        "CMP E",
        "CMP H",
        "CMP L",
        "CMP M",
        "CMP A",
        "RNZ",
        "POP B",
        "JNZ adr",
        "JMP adr",
        "CNZ adr",
        "PUSH B",
        "ADI D8",
        "RST 0",
        "RZ",
        "RET",
        "JZ adr",
        "-",
        "CZ adr",
        "CALL adr",
        "ACI D8",
        "RST 1",
        "RNC",
        "POP D",
        "JNC adr",
        "OUT D8",
        "CNC adr",
        "PUSH D",
        "SUI D8",
        "RST 2",
        "RC",
        "-",
        "JC adr",
        "IN D8",
        "CC adr",
        "-",
        "SBI D8",
        "RST 3",
        "RPO",
        "POP H",
        "JPO adr",
        "XTHL",
        "CPO adr",
        "PUSH H",
        "ANI D8",
        "RST 4",
        "RPE",
        "PCHL",
        "JPE adr",
        "XCHG",
        "CPE adr",
        "-",
        "XRI D8",
        "RST 5",
        "RP",
        "POP PSW",
        "JP adr",
        "DI",
        "CP adr",
        "PUSH PSW",
        "ORI D8",
        "RST 6",
        "RM",
        "SPHL",
        "JM adr",
        "EI",
        "CM adr",
        "-",
        "CPI D8",
        "RST 7"
    };

    char instructionSizesLocal[256] = {
        1,
        3,
        1,
        1,
        1,
        1,
        2,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        2,
        1,
        0,
        3,
        1,
        1,
        1,
        1,
        2,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        2,
        1,
        1,
        3,
        3,
        1,
        1,
        1,
        2,
        1,
        0,
        1,
        3,
        1,
        1,
        1,
        2,
        1,
        1,
        3,
        3,
        1,
        1,
        1,
        2,
        1,
        0,
        1,
        3,
        1,
        1,
        1,
        2,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        3,
        3,
        3,
        1,
        2,
        1,
        1,
        1,
        3,
        0,
        3,
        3,
        2,
        1,
        1,
        1,
        3,
        2,
        3,
        1,
        2,
        1,
        1,
        0,
        3,
        2,
        3,
        0,
        2,
        1,
        1,
        1,
        3,
        1,
        3,
        1,
        2,
        1,
        1,
        1,
        3,
        1,
        3,
        0,
        2,
        1,
        1,
        1,
        3,
        1,
        3,
        1,
        2,
        1,
        1,
        1,
        3,
        1,
        3,
        0,
        2,
        1
    };

    char instructionFlagsLocal[256][20] = {
        "",
        "",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "CY",
        "",
        "CY",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "CY",
        "",
        "",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "CY",
        "",
        "CY",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "CY",
        "",
        "",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "",
        "",
        "CY",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "CY",
        "",
        "CY",
        "",
        "",
        "Z; S; P; AC",
        "Z; S; P; AC",
        "",
        "CY",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Z; S; P; CY; AC",
        ""
    };

    char instructionFunctionsLocal[256][100] = {
        "",
        "B &lt;- byte 3; C &lt;- byte 2",
        "(BC) &lt;- A",
        "BC &lt;- BC+1",
        "B &lt;- B+1",
        "B &lt;- B-1",
        "B &lt;- byte 2",
        "A = A &lt;&lt; 1; bit 0 = prev bit 7; CY = prev bit 7",
        "",
        "HL = HL + BC",
        "A &lt;- (BC)",
        "BC = BC-1",
        "C &lt;- C+1",
        "C &lt;-C-1",
        "C &lt;- byte 2",
        "A = A &gt;&gt; 1; bit 7 = prev bit 0; CY = prev bit 0",
        "",
        "D &lt;- byte 3; E &lt;- byte 2",
        "(DE) &lt;- A",
        "DE &lt;- DE + 1",
        "D &lt;- D+1",
        "D &lt;- D-1",
        "D &lt;- byte 2",
        "A = A &lt;&lt; 1; bit 0 = prev CY; CY = prev bit 7",
        "",
        "HL = HL + DE",
        "A &lt;- (DE)",
        "DE = DE-1",
        "E &lt;-E+1",
        "E &lt;- E-1",
        "E &lt;- byte 2",
        "A = A &gt;&gt; 1; bit 7 = prev bit 7; CY = prev bit 0",
        "special",
        "H &lt;- byte 3; L &lt;- byte 2",
        "(adr) &lt;-L; (adr+1)&lt;-H",
        "HL &lt;- HL + 1",
        "H &lt;- H+1",
        "H &lt;- H-1",
        "L &lt;- byte 2",
        "special",
        "",
        "HL = HL + HI",
        "L &lt;- (adr); H&lt;-(adr+1)",
        "HL = HL-1",
        "L &lt;- L+1",
        "L &lt;- L-1",
        "L &lt;- byte 2",
        "A &lt;- !A",
        "special",
        "SP.hi &lt;- byte 3; SP.lo &lt;- byte 2",
        "(adr) &lt;- A",
        "SP = SP + 1",
        "(HL) &lt;- (HL)+1",
        "(HL) &lt;- (HL)-1",
        "(HL) &lt;- byte 2",
        "CY = 1",
        "",
        "HL = HL + SP",
        "A &lt;- (adr)",
        "SP = SP-1",
        "A &lt;- A+1",
        "A &lt;- A-1",
        "A &lt;- byte 2",
        "CY=!CY",
        "B &lt;- B",
        "B &lt;- C",
        "B &lt;- D",
        "B &lt;- E",
        "B &lt;- H",
        "B &lt;- L",
        "B &lt;- (HL)",
        "B &lt;- A",
        "C &lt;- B",
        "C &lt;- C",
        "C &lt;- D",
        "C &lt;- E",
        "C &lt;- H",
        "C &lt;- L",
        "C &lt;- (HL)",
        "C &lt;- A",
        "D &lt;- B",
        "D &lt;- C",
        "D &lt;- D",
        "D &lt;- E",
        "D &lt;- H",
        "D &lt;- L",
        "D &lt;- (HL)",
        "D &lt;- A",
        "E &lt;- B",
        "E &lt;- C",
        "E &lt;- D",
        "E &lt;- E",
        "E &lt;- H",
        "E &lt;- L",
        "E &lt;- (HL)",
        "E &lt;- A",
        "H &lt;- B",
        "H &lt;- C",
        "H &lt;- D",
        "H &lt;- E",
        "H &lt;- H",
        "H &lt;- L",
        "H &lt;- (HL)",
        "H &lt;- A",
        "L &lt;- B",
        "L &lt;- C",
        "L &lt;- D",
        "L &lt;- E",
        "L &lt;- H",
        "L &lt;- L",
        "L &lt;- (HL)",
        "L &lt;- A",
        "(HL) &lt;- B",
        "(HL) &lt;- C",
        "(HL) &lt;- D",
        "(HL) &lt;- E",
        "(HL) &lt;- H",
        "(HL) &lt;- L",
        "special",
        "(HL) &lt;- C",
        "A &lt;- B",
        "A &lt;- C",
        "A &lt;- D",
        "A &lt;- E",
        "A &lt;- H",
        "A &lt;- L",
        "A &lt;- (HL)",
        "A &lt;- A",
        "A &lt;- A + B",
        "A &lt;- A + C",
        "A &lt;- A + D",
        "A &lt;- A + E",
        "A &lt;- A + H",
        "A &lt;- A + L",
        "A &lt;- A + (HL)",
        "A &lt;- A + A",
        "A &lt;- A + B + CY",
        "A &lt;- A + C + CY",
        "A &lt;- A + D + CY",
        "A &lt;- A + E + CY",
        "A &lt;- A + H + CY",
        "A &lt;- A + L + CY",
        "A &lt;- A + (HL) + CY",
        "A &lt;- A + A + CY",
        "A &lt;- A - B",
        "A &lt;- A - C",
        "A &lt;- A + D",
        "A &lt;- A - E",
        "A &lt;- A + H",
        "A &lt;- A - L",
        "A &lt;- A + (HL)",
        "A &lt;- A - A",
        "A &lt;- A - B - CY",
        "A &lt;- A - C - CY",
        "A &lt;- A - D - CY",
        "A &lt;- A - E - CY",
        "A &lt;- A - H - CY",
        "A &lt;- A - L - CY",
        "A &lt;- A - (HL) - CY",
        "A &lt;- A - A - CY",
        "A &lt;- A &amp; B",
        "A &lt;- A &amp; C",
        "A &lt;- A &amp; D",
        "A &lt;- A &amp; E",
        "A &lt;- A &amp; H",
        "A &lt;- A &amp; L",
        "A &lt;- A &amp; (HL)",
        "A &lt;- A &amp; A",
        "A &lt;- A ^ B",
        "A &lt;- A ^ C",
        "A &lt;- A ^ D",
        "A &lt;- A ^ E",
        "A &lt;- A ^ H",
        "A &lt;- A ^ L",
        "A &lt;- A ^ (HL)",
        "A &lt;- A ^ A",
        "A &lt;- A | B",
        "A &lt;- A | C",
        "A &lt;- A | D",
        "A &lt;- A | E",
        "A &lt;- A | H",
        "A &lt;- A | L",
        "A &lt;- A | (HL)",
        "A &lt;- A | A",
        "A - B",
        "A - C",
        "A - D",
        "A - E",
        "A - H",
        "A - L",
        "A - (HL)",
        "A - A",
        "if NZ; RET",
        "C &lt;- (sp); B &lt;- (sp+1); sp &lt;- sp+2",
        "if NZ; PC &lt;- adr",
        "PC &lt;= adr",
        "if NZ; CALL adr",
        "(sp-2)&lt;-C; (sp-1)&lt;-B; sp &lt;- sp - 2",
        "A &lt;- A + byte",
        "CALL $0",
        "if Z; RET",
        "PC.lo &lt;- (sp); PC.hi&lt;-(sp+1); SP &lt;- SP+2",
        "if Z; PC &lt;- adr",
        "",
        "if Z; CALL adr",
        "(SP-1)&lt;-PC.hi;(SP-2)&lt;-PC.lo;SP&lt;-SP+2;PC=adr",
        "A &lt;- A + data + CY",
        "CALL $8",
        "if NCY; RET",
        "E &lt;- (sp); D &lt;- (sp+1); sp &lt;- sp+2",
        "if NCY; PC&lt;-adr",
        "special",
        "if NCY; CALL adr",
        "(sp-2)&lt;-E; (sp-1)&lt;-D; sp &lt;- sp - 2",
        "A &lt;- A - data",
        "CALL $10",
        "if CY; RET",
        "",
        "if CY; PC&lt;-adr",
        "special",
        "if CY; CALL adr",
        "",
        "A &lt;- A - data - CY",
        "CALL $18",
        "if PO; RET",
        "L &lt;- (sp); H &lt;- (sp+1); sp &lt;- sp+2",
        "if PO; PC &lt;- adr",
        "L &lt;-&gt; (SP); H &lt;-&gt; (SP+1) ",
        "if PO; CALL adr",
        "(sp-2)&lt;-L; (sp-1)&lt;-H; sp &lt;- sp - 2",
        "A &lt;- A &amp; data",
        "CALL $20",
        "if PE; RET",
        "PC.hi &lt;- H; PC.lo &lt;- L",
        "if PE; PC &lt;- adr",
        "H &lt;-&gt; D; L &lt;-&gt; E",
        "if PE; CALL adr",
        "",
        "A &lt;- A ^ data",
        "CALL $28",
        "if P; RET",
        "flags &lt;- (sp); A &lt;- (sp+1); sp &lt;- sp+2",
        "if P=1 PC &lt;- adr",
        "special",
        "if P; PC &lt;- adr",
        "(sp-2)&lt;-flags; (sp-1)&lt;-A; sp &lt;- sp - 2",
        "A &lt;- A | data",
        "CALL $30",
        "if M; RET",
        "SP=HL",
        "if M; PC &lt;- adr",
        "special",
        "if M; CALL adr",
        "",
        "A - data",
        "CALL $38"
    };

    memcpy(instructions, instructionsLocal, 256*20);
    memcpy(instructionSizes, instructionSizesLocal, 256);
    memcpy(instructionFlags, instructionFlagsLocal, 256*20);
    memcpy(instructionFunctions, instructionFunctionsLocal, 256*100);
}